# Generated by Django 2.2 on 2022-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarDBConfig',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('selectedTables', models.CharField(blank=True, max_length=1100, null=True)),
                ('host', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('database', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
